MySQL:
  Host: localhost
  Port: 3306
  Username: root
  Password: minecraft
  Database: GenshinShop
  TablePrefix: GenshinShop
  DummyData:
    enable: true
    period: 300

shops:
  - ExampleShop.yml
